[server]
	port = 3000

[store]
	db_uri = "nedb:////Users/jonathan/Projects/pi-clock/data/piclock.db"
	sounds_dir = "./data/sounds"

[audio]
	player = 'afplay'
	extensions = ['.mp3', '.wav']
# Should this even be a config?
	players = [
		'mplayer',
		'afplay',
		'mpg123',
		'mpg321',
		'play',
		'omxplayer',
		'aplay',
		'cmdmp3'
	]

# A kind of hacky whitelist of valid vendor libraries to send to clients.
# These are files that can be loaded via a `/vendors/some_file` endpoint.
# The key is the "some_file" path component, while the value is the on-disk path.
# Underscores are replaced with dots.
[vendor]
	io-d47abd80_js = "redux-saga/dist/io-d47abd80.js"
	io-f9ca3938_js = "redux-saga/dist/io-f9ca3938.js"
	react_js = "react/umd/react.development.js"
	react-dom_js = "react-dom/umd/react-dom.development.js"
	redux_js = "redux/dist/redux.js"
	react-redux_js = "react-redux/dist/react-redux.js"
	redux-saga_js = "redux-saga/dist/redux-saga-core.esmodules-browsers.js"
	redux-saga-effects_js = "redux-saga/dist/redux-saga-effects.esmodules-browsers.js"
	moment_js = "moment/moment.js"
	htm_mjs = "htm/dist/htm.mjs"
	htm-react_mjs = "htm/react/index.mjs"
	socket_io_js = "socket.io-client/dist/socket.io.js"
